/* eslint-disable react-hooks/exhaustive-deps */
import Head from "next/head";
import Swiper from "../components/swiper";
import Delivery from "@/components/delivery";
import Categories from "@/components/categories";
import Bestdeals from "@/components/bestdeals";
import Topproducts from "@/components/topproducts";
import ProductFilter from "@/components/productFilter";
import TopRated from "@/components/flashdeals";
import { useSelector } from "react-redux";
import { Skeleton, Spin } from "antd";
import { useState } from "react";
import { LoadingOutlined, ReloadOutlined } from "@ant-design/icons";
import SyncIcon from "@mui/icons-material/Sync";
import { getDashProfile } from "@/helper/utilities/apiHelper";
import { useEffect } from "react";
import { get } from "lodash";
import { useDispatch } from "react-redux";

export default function Home() {
  const isLoading = useSelector((state) => state.loader.isLoading);
  const [colors, setColor] = useState([]);
  const dispatch = useDispatch();
  const result = useSelector((data) => {
    return data.search.searches;
  });

  const fetchData = async () => {
    try {
      const result = await getDashProfile();
      setColor(get(result, "data.data[0]"));
    } catch (err) {
      console.log(err);
    }
  };

  useEffect(() => {
    document.documentElement.style.setProperty(
      "--second-color",
      colors.primary
    );
    document.documentElement.style.setProperty(
      "--fifth-color",
      colors.secondary
    );
    document.documentElement.style.setProperty("--third-color", colors.primary);
    console.log(
      document.documentElement.style,
      "document.documentElement.style"
    );
    fetchData();
  }, [colors.primary]);

  const antIcon = (
    <ReloadOutlined style={{ fontSize: 40 }} className="animate-spin" />
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Spin
          spinning={isLoading}
          tip="Loading Datas..."
          size="large"
          indicator={antIcon}
        >
          <div>
            {result.length > 0 ? (
              <ProductFilter />
            ) : (
              <>
                <Swiper />
                <Delivery />
                <Categories />
                <Bestdeals />
                <TopRated />
                <Topproducts />
              </>
            )}
          </div>
        </Spin>
      </main>
    </>
  );
}
